//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agribusiness.WS.CrpService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CouponTypes", Namespace="http://schemas.datacontract.org/2004/07/CRP.Services.Wcf")]
    public enum CouponTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unlimited = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LimitedUsage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleUsage = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceTransaction", Namespace="http://schemas.datacontract.org/2004/07/CRP.Services.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agribusiness.WS.CrpService.ServiceQuestion[] ServiceQuestionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Paid {
            get {
                return this.PaidField;
            }
            set {
                if ((this.PaidField.Equals(value) != true)) {
                    this.PaidField = value;
                    this.RaisePropertyChanged("Paid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agribusiness.WS.CrpService.ServiceQuestion[] ServiceQuestions {
            get {
                return this.ServiceQuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceQuestionsField, value) != true)) {
                    this.ServiceQuestionsField = value;
                    this.RaisePropertyChanged("ServiceQuestions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceQuestion", Namespace="http://schemas.datacontract.org/2004/07/CRP.Services.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> QuantityIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> QuantityIndex {
            get {
                return this.QuantityIndexField;
            }
            set {
                if ((this.QuantityIndexField.Equals(value) != true)) {
                    this.QuantityIndexField = value;
                    this.RaisePropertyChanged("QuantityIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrpService.IItemService")]
    public interface IItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/CreateCoupon", ReplyAction="http://tempuri.org/IItemService/CreateCouponResponse")]
        string CreateCoupon(int itemId, string email, System.Nullable<System.DateTime> expiration, decimal discountAmount, System.Nullable<int> maxUsage, System.Nullable<int> maxQuantity, Agribusiness.WS.CrpService.CouponTypes couponTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/CancelCoupon", ReplyAction="http://tempuri.org/IItemService/CancelCouponResponse")]
        bool CancelCoupon(int itemId, string couponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetRegistrationByReference", ReplyAction="http://tempuri.org/IItemService/GetRegistrationByReferenceResponse")]
        Agribusiness.WS.CrpService.ServiceTransaction GetRegistrationByReference(string registrationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetRegistrationById", ReplyAction="http://tempuri.org/IItemService/GetRegistrationByIdResponse")]
        Agribusiness.WS.CrpService.ServiceTransaction GetRegistrationById(int transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetRegistrations", ReplyAction="http://tempuri.org/IItemService/GetRegistrationsResponse")]
        Agribusiness.WS.CrpService.ServiceTransaction[] GetRegistrations(int itemId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemServiceChannel : Agribusiness.WS.CrpService.IItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemServiceClient : System.ServiceModel.ClientBase<Agribusiness.WS.CrpService.IItemService>, Agribusiness.WS.CrpService.IItemService {
        
        public ItemServiceClient() {
        }
        
        public ItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateCoupon(int itemId, string email, System.Nullable<System.DateTime> expiration, decimal discountAmount, System.Nullable<int> maxUsage, System.Nullable<int> maxQuantity, Agribusiness.WS.CrpService.CouponTypes couponTypes) {
            return base.Channel.CreateCoupon(itemId, email, expiration, discountAmount, maxUsage, maxQuantity, couponTypes);
        }
        
        public bool CancelCoupon(int itemId, string couponCode) {
            return base.Channel.CancelCoupon(itemId, couponCode);
        }
        
        public Agribusiness.WS.CrpService.ServiceTransaction GetRegistrationByReference(string registrationId) {
            return base.Channel.GetRegistrationByReference(registrationId);
        }
        
        public Agribusiness.WS.CrpService.ServiceTransaction GetRegistrationById(int transactionId) {
            return base.Channel.GetRegistrationById(transactionId);
        }
        
        public Agribusiness.WS.CrpService.ServiceTransaction[] GetRegistrations(int itemId) {
            return base.Channel.GetRegistrations(itemId);
        }
    }
}
