insert into seminars ([year], location, [begin], [end]) values (1989, 'n/a', '1/1/1989', '1/1/1989')
insert into seminars ([year], location, [begin], [end]) values (1990, 'n/a', '1/1/1990', '1/1/1990')
insert into seminars ([year], location, [begin], [end]) values (1992, 'n/a', '1/1/1992', '1/1/1992')
insert into seminars ([year], location, [begin], [end]) values (1995, 'n/a', '1/1/1995', '1/1/1995')
insert into seminars ([year], location, [begin], [end]) values (1996, 'n/a', '1/1/1996', '1/1/1996')
insert into seminars ([year], location, [begin], [end]) values (1998, 'n/a', '1/1/1989', '1/1/1998')

declare @seminarId int

set @seminarId = (select max(id) from seminars where year = '1989')
insert into casestudies (name, seminarid, ispublic) values ('Glen Ellen Winery', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Ed Sills & the CA Organic Food Industry (Sills  Farm)', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Blackwell Land Co.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Sun-Maid Raisin Growers of CA', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Blue Diamond Growers-The Almond People', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Diamond-S Ranch: Dairy Production in a  Changing Environment', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Merchants Cotton Co. (A) (Dunavant)', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Mann Packing Co.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Riverbend International Corp.', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '1990')
insert into casestudies (name, seminarid, ispublic) values ('A.H. Rominger & Sons Farm', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Norcal/Crosetti Frozen Foods', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Save Mart Supermarkets, Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Sunkist Growers Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('California Canning Peach Association', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Ingomar Packing Co.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Don Jackson & the CA Beef Industry', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Norcal', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('CA Tomato Growers Association', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '1992')
insert into casestudies (name, seminarid, ispublic) values ('Nectarine Marketing Order', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('CA Water Bank', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Freemark Abbey Winery', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Eel River Sawmills, INC.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Calavo Growers of CA', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '1995')
insert into casestudies (name, seminarid, ispublic) values ('Arvin Edison Water Storage District', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Calgene', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Conagra Wool PTY LTD', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Cott Corporation', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Efficient Consumer Response (ECR)', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Hormel Foods Corporation', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Morning Star', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Sunkist Grower''s Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Wells Fargo Bank', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '1996')
insert into casestudies (name, seminarid, ispublic) values ('The Gowan Co.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Vista Verde Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Land O'' Lakes', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Chalice Wines Joint Venture', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Fresh Express Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Wild Oats Community Market', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Nulaid Foods Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Erly Industries', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '1998')
insert into casestudies (name, seminarid, ispublic) values ('Muir Glen Organic Tomato Products', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Duckhorn Vineyards', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('California Table Grape Commission', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Odwall Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Foster Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Scheid Vineyards, Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Juanita''s Foods', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Cadiz Land Co. Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Dreyer''s Grand Ice Cream, Inc.', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('CA Wine and Grape Industry', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '2000')
insert into casestudies (name, seminarid, ispublic) values ('Corcoran Cotton Company', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Precision Farming Company', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Woolf Farming Company', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Next Nutraceuticals', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Barkley Seed Company', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('U.S. Citrus Science Council', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Harris Ranch Beef Industry Case', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Agribuys.com', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Peapod.com', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '2002')
insert into casestudies (name, seminarid, ispublic) values ('Circle G Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('California Tomato Growers Association', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Westcot Ginning Co./International Cotton', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Del Monte Foods Company', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Beringer Blass Wine Estates', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Tri Valley Growers', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Monte Vista Farming Company', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '2004')
insert into casestudies (name, seminarid, ispublic) values ('Royal Dutch Ahold', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Wal-Mart', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('International Trade & California Agribusiness', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('California Water', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Global Berry Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('The Future of Cooperatives in California Agriculture', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '2006')
insert into casestudies (name, seminarid, ispublic) values ('China''s Ag Development', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Alternative Retail Formats', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Village Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Sound Science', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('U.S. Foodservice', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Whole Foods', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Obesity', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Frog Hollow Farm', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '2008')
insert into casestudies (name, seminarid, ispublic) values ('Wild Rocket Foods/Tesco', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Mendocino Wine Company', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Imagination Farms/Disney', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Hannaford Brothers', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Craton Capital/Biofuels', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Labor/Immigration', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Stemilt Growers', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Food Safety', @seminarId, 1)

set @seminarId = (select max(id) from seminars where year = '2010')
insert into casestudies (name, seminarid, ispublic) values ('Social Media', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Schnucks', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Blue Diamond Growers', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Taylor Farms', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Ag Cycles', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Kroger', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Water', @seminarId, 1)
insert into casestudies (name, seminarid, ispublic) values ('Information Technology', @seminarId, 1)