//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agribusiness.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticIndexes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticIndexes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agribusiness.Web.App_GlobalResources.StaticIndexes", typeof(StaticIndexes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Address_Business {
            get {
                return ResourceManager.GetString("Address_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Address_Courier {
            get {
                return ResourceManager.GetString("Address_Courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        public static string Communication_Assistant {
            get {
                return ResourceManager.GetString("Communication_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        public static string Communication_CCAssistant {
            get {
                return ResourceManager.GetString("Communication_CCAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DR.
        /// </summary>
        public static string Communication_Directly {
            get {
                return ResourceManager.GetString("Communication_Directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatbertCritical.
        /// </summary>
        public static string Key_CatbertCritical {
            get {
                return ResourceManager.GetString("Key_CatbertCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatbertMessage.
        /// </summary>
        public static string Key_CatbertMessage {
            get {
                return ResourceManager.GetString("Key_CatbertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessages.
        /// </summary>
        public static string Key_ErrorMessage {
            get {
                return ResourceManager.GetString("Key_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Key_Message {
            get {
                return ResourceManager.GetString("Key_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        public static string Role_CaseExecutive {
            get {
                return ResourceManager.GetString("Role_CaseExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        public static string Role_CaseStudyAuthor {
            get {
                return ResourceManager.GetString("Role_CaseStudyAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL.
        /// </summary>
        public static string Role_DiscussionGroupLeader {
            get {
                return ResourceManager.GetString("Role_DiscussionGroupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FD.
        /// </summary>
        public static string Role_FacultyDirector {
            get {
                return ResourceManager.GetString("Role_FacultyDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PN.
        /// </summary>
        public static string Role_Panelist {
            get {
                return ResourceManager.GetString("Role_Panelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        public static string Role_Participant {
            get {
                return ResourceManager.GetString("Role_Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.
        /// </summary>
        public static string Role_Speaker {
            get {
                return ResourceManager.GetString("Role_Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        public static string Role_Staff {
            get {
                return ResourceManager.GetString("Role_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.
        /// </summary>
        public static string Role_SteeringCommittee {
            get {
                return ResourceManager.GetString("Role_SteeringCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VD.
        /// </summary>
        public static string Role_Vendor {
            get {
                return ResourceManager.GetString("Role_Vendor", resourceCulture);
            }
        }
    }
}
