ALTER TABLE [dbo].[ApplicationXCommodity]
    ADD CONSTRAINT [PK_ApplicationXCommodity] PRIMARY KEY CLUSTERED ([ApplicationId] ASC, [CommodityId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

