ALTER TABLE [dbo].[EmailQueueXAttachments]
    ADD CONSTRAINT [PK_EmailQueueXAttachments] PRIMARY KEY CLUSTERED ([EmailQueueId] ASC, [AttachmentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

