ALTER TABLE [dbo].[MailingListsXPeople]
    ADD CONSTRAINT [PK_MailingListsXPeople] PRIMARY KEY CLUSTERED ([MailingListId] ASC, [PersonId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

