ALTER TABLE [dbo].[SeminarPeopleXSeminarRoles]
    ADD CONSTRAINT [PK_SeminarPeopleXSeminarRoles] PRIMARY KEY CLUSTERED ([SeminarPersonId] ASC, [SeminarRoleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

