ALTER TABLE [dbo].[SeminarPeopleXSessions]
    ADD CONSTRAINT [PK_SeminarPeopleSessions] PRIMARY KEY CLUSTERED ([SeminarPersonId] ASC, [SessionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

