ALTER TABLE [dbo].[SeminarPeopleXCommodities]
    ADD CONSTRAINT [PK_SeminarPersonXCommodity] PRIMARY KEY CLUSTERED ([SeminarPersonId] ASC, [CommodityId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

