ALTER TABLE [dbo].[SessionPeople]
    ADD CONSTRAINT [PK_SessionPeople] PRIMARY KEY CLUSTERED ([SessionId] ASC, [SeminarPersonId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

